### PR TITLE
Prompt user to enter location if not entered on clicking the generate Button

### PR DESCRIPTION
**Pull request by yatna**
Earlier in the trip planner the reminder was generated even if the location was left empty. This created a incomplete remainder message. Now the user has to first enter the location to set a remainder. A toast message i displayed if the location is not set.

### CODE REVIEW

**Comment by ankita-kalra** [comment]
Its a good point noticed, but generally its intuitive to fill form in order. To remove this vulnerability, its better if we make a check that if anyone of the fields is empty, prompt the user to complete the form.

**Comment by rosariorobinson** [comment]
Where are we on this PR @ankita-kalra?

**Comment by yatna** [comment]
As pointed out , now the entire form is checked and if any of the fields is found empty, the user is prompted to complete that particular field.

**Comment by ankita-kalra** [comment]
Good work!

It would be better if you add an error to edit text if the field is empty instead of a toast. Something like below.

android-seterror

**Comment by yatna** [comment]
Toast have been replaced using setError() functions which look exactly as above:
screenshot_2015-12-20-18-41-44
screenshot_2015-12-20-18-42-18

**Comment by yatna** [comment]
This branch will automatically resolve merge conflicts as soon as #12 is merged. Currently giving merge conflicts as both PR are changing the same file.

**Comment by ankita-kalra** [comment]
Still had conflicts after merging #20, so have reverted #20 . Close #13 and #20 and create a single PR to this branch with changes as specified in both.

**Comment by yatna** [comment]
New PR sent #37 with merge conflicts resolved. Closing this PR.

**Pull request closed without merging**
