### PR TITLE
Deleted all the unused drawable files

### LINKED ISSUE #74: Removal of unneccesary drawables
Copies of the same drawable has been maintained who just vary with respect to their sizes,color and opacity. These all can be implemented dynamically in their respective activities showing their current status via following methods invoked on the buttons after setting their background:

a)setAlpha(float value)                                        
b)setHighlightColor(int color)
c)setLayoutParams(LayoutParams param)

This highly reduces the number of copies made , for instance for all the buttons showing active and inactive state and many others like checked or not checked,etc.

### PR DESCRIPTION
**Pull request by yatri1609**
Fixes #74 
Deleted all the unused and unnecessary drawable files.

## Type of Change:
* Maintainance : Removing unused files

## Checklist
- [x] My PR follows the style guidelines of this project
- [x] Any dependent changes have been merged
- [x] I have performed a self-review of my own code or materials

### CODE REVIEW

**Comment by yatri1609** [comment]
@geekanamika Can you please review this PR?

**Comment by geekanamika** [comment]
@yatri1609 How did you recognize unused drawables? Any reference? Since, travis builds successfully, you haven't removed any used resource but How did you made sure that you have removed all of the unused drawables?[Asking for learning purpose]

**Comment by yatri1609** [comment]
@geekanamika I checked whether each of the drawable file is used or not in the whole android project using the option of Find Usage (ALT+F7).

**Review by geekanamika — APPROVED** [review]
Looks good, It'll help in reducing app+project size.

**Review by r00pal — APPROVED** [review]

**Pull request merged**
