### PR TITLE
Fixed back button to go to Main Activity

### PR DESCRIPTION
**Pull request by InfernoCoder**
Done the GCI task to go back to the main activity when back button is pressed.

### CODE REVIEW

**Comment by yatna** [comment]
@InfernoCoder Please reference the issue this PR is made for.

**Comment by InfernoCoder** [comment]
@yatna  I cannot find the issue for this PR. I have attached a screenshot of the GCI task -
screenshot_20161221-162205

**Comment by chhavip** [comment]
@InfernoCoder , you do not need to start the MainActivity again from each of the activities but rather fix the finish() of MainAcitivity when it calls the other activities. Please re-check the code.

**Comment by InfernoCoder** [comment]
@chhavip Ok, uploading a new commit soon

**Comment by InfernoCoder** [comment]
@chhavip Done

**Comment by chhavip** [comment]
Good work! Approving the GCI task.

**Comment by chhavip** [comment]
This PR is ready-to-merge, closing now to be looked over after GCI.

**Comment by InfernoCoder** [comment]
Thanks

**Pull request closed without merging**
