### PR TITLE
Fixed layout distortion in TripIndicatorFragmentActivity

### PR DESCRIPTION
**Pull request by jaiagarwal**
The layout get distorted in TripIndicatorFragmentActivity when soft keyboard is inflated. 

Before: 

 &nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp;     sc1 &nbsp;  &nbsp;   &nbsp;&nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp;    sc2

After:

&nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp;   sc3

### CODE REVIEW

**Comment by jaiagarwal** [comment]
Extra commit is reverted and I've created a new PR for the new commit.

**Comment by yatna** [comment]
@jaiagarwal If you can please resolve the conflicts , we would like to merge this.

**Comment by free4murad** [comment]
@yatna If this is issue is open, can I work on this??

**Comment by yatna** [comment]
Since, the issue has already been solved in this PR, there is no work to be done. We, will wait for the author to remove the merge conflicts and then merge the PR. If not, we will resolve the merge conflict ourselves and merge anyways.

**Comment by chhavip** [comment]
@yatna , how long do you believe would be appropriate to wait for the original author? We should make this an open issue or merge changes ourselves soon otherwise.

**Comment by yatna** [comment]
@chhavip Since, it has been more than a couple of days, I think we should now merge the changes ourselves. Since, the issue requires only 1 line of code change and too is displayed in this PR, making it an issue would not be fair.

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #256

**Pull request closed without merging**
