### PR TITLE
Bug in RapidFireGame solved

### PR DESCRIPTION
**Pull request by sridharjajoo**
While playing the quiz once an option is selected others will get automatically disabled.

### CODE REVIEW

**Comment by yatna** [comment]
@sridharjajoo Why are the .idea files being changed?

**Comment by sridharjajoo** [comment]
They weren't changed ...they were untracked so I added them

**Comment by yatna** [comment]
@sridharjajoo Your Android Studio might have changed it, I think it will be better to add only those files which are related to the issue. You can remove the extra files, i.e keep only the RapidFireGame.java and its corresponding .xml file. Rest all looks good, keep up the good work. 
Just make changes and resend the PR with a single commit.

**Comment by yatna** [comment]
@sridharjajoo Squash both the commits to a single commit, as there should be only one commit per task.

**Comment by sridharjajoo** [comment]
@yatna I have created another PR where i have committed the changes on a different branch.

**Comment by chhavip** [comment]
This can be closed then @yatna @sridharjajoo , right?

**Pull request closed without merging**
