### PR TITLE
Correct no. drugs calculated for trip on TripIndicatorFragmentActivity

### PR DESCRIPTION
**Pull request by yatna**
Number of drugs required for trip were calculated incorrectly.
Example
 for 1 Jan 2015 to 1 Feb 2015 ...Numbers of dugs=1;
 for 1 Jan 2015 to to 2 Jan 2015  ....Numbers of dugs=31;
This was because the month and day were flipped which  gave wrong calculations.
Fixed the bug . Now 
 for 1 Jan 2015 to 1 Feb 2015 ...Numbers of dugs=31;
 for 1 Jan 2015 to to 2 Jan 2015  ....Numbers of dugs=1;

Also reduced the textsize of the textview displaying Number of medicines on trip_indicator_packing_dialog, as earlier it was showing maximum upto 2 digits. Rest of the digit were getting hidden due to lack of space. Thus 365 appeared as 36. 
After textsize reduction the problem is solved.

### CODE REVIEW

**Comment by yatna** [comment]
Drug selected was daily.
Problem arose because the display date was in MM/DD/YYYY format whereas internally calculations were being made by dd/mm/yyyy format.(  SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");). Swapping dd with mm gave the correct calculation.

**Comment by ankita-kalra** [comment]
check for the weekly drug also, and update on this

**Comment by ankita-kalra** [comment]
for 1 Jan 2015 to 1 Feb 2015 ...Numbers of dugs=31;
for 1 Jan 2015 to to 2 Jan 2015 ....Numbers of dugs=1;

Add this test case in MalariaDatabaseTest.java and check result for weekly drug.

**Comment by yatna** [comment]
As told by you, now the number of drugs to be carried during the trip depend on the drug chosen by the user in the TripIndicatorPackingActivity.

For a trip from 1/1/2016 to 7/1/2016 (1 week):
malarone (daily) ---> 7
Doxycycline, Mefloquine (weekly)---> 1

For a trip from 1/1/2016 to 8/1/2016 (1 week +1 day):
malarone (daily) ---> 8
Doxycycline, Mefloquine (weekly) ---> 2

**Comment by yatna** [comment]
This branch now has no conflicts.

**Comment by yatna** [comment]
New PR sent #37.

**Pull request merged**
