### PR TITLE
Fixes#47:Added all the hardcoded dimensions to dimens.xml file

### LINKED ISSUE #47: Adding hardcoded integers, strings to dimens.xml and strings.xml
I would like to add all the hard coded dimensions and strings to dimens.xml and strings.xml

### PR DESCRIPTION
**Pull request by HimanshuS01**
Fixes #47 
Removed all hardcoded dimensions(width, height, layouts margins, layouts padding etc) from all  **xml** files to **dimens.xml**. 
One part of this issue has been solved In #223.

@chhavip @anubhakushwaha @yatna please review this PR. 
Thank you :)

### CODE REVIEW

**Comment by HimanshuS01** [comment]
@yatna @chhavip @anubhakushwaha Please review this PR. :)

**Comment by HimanshuS01** [comment]
@anubhakushwaha Please review this PR :)

**Comment by anubhakushwaha** [comment]
@HimanshuS01 I am planning to merge it after other approved PR's in order to avoid merge conflicts as these files will be in all the submitted PR's.

**Comment by HimanshuS01** [comment]
Sure @anubhakushwaha no problem :)

**Pull request closed without merging**
