### PR TITLE
fixed issue #160 : share dialogue box pops up when the button says email

### PR DESCRIPTION
**Pull request by vaibhavchellani**
share dialogue box pops up when the button says email 
issue #160 fixed

### CODE REVIEW

**Comment by anubhakushwaha** [comment]
@vaibhavchellani Please give a meaningful commit message which describes the work done

**Comment by yatna** [comment]
@vaibhavchellani Also attach a screenshot of the new chooser which pops up.

**Comment by vaibhavchellani** [comment]
@yatna @anubhakushwaha  thanks for approving the PR.
Can you please give an example showing what the commit message should be like , also how long should it be ?
Thank  You

**Comment by anubhakushwaha** [comment]
@vaibhavchellani Just the problem it solved like " corrected dialog popup showing only email apps via email option"

**Pull request merged**
