### PR TITLE
GSoC 2016 adt

### PR DESCRIPTION
**Pull request by yatna**

### CODE REVIEW

**Comment by ankita-kalra** [comment]
@yatna 

have you added a new readme? why is this #461e6c7 removed?

**Comment by ankita-kalra** [comment]
+1 @rosariorobinson 
I have reviewed the code. Looks good.

**Comment by ankita-kalra** [comment]
Trying merge with command line as there are conflicts,

**Comment by MeepyMay** [comment]
Can you switch this branch from systers:master to systers:develop?

**Pull request merged**
