### PR TITLE
Correct layout for names of months

### LINKED ISSUE #106: Correct alignment of months name
Currently the months' names displayed in the last tab of Malaria Home Screen tend to overflow to next line in case of lack of space. Adjust name of month and progress bar as to fit in a single line or name of month in one line and progress in the next.

### PR DESCRIPTION
**Pull request by FarbodSalamat-Zadeh**
Resolves #106

### CODE REVIEW

**Comment by FarbodSalamat-Zadeh** [comment]
@yatna This is for GCI 2016 - I have now edited my original PR description to reference the issue this resolves.

**Comment by FarbodSalamat-Zadeh** [comment]
I've improved the layout spacing using `RelativeLayout` and also optimized the `land` layout. The use of the `<include>` tag also reduces the amount of code significantly.

**Comment by chhavip** [comment]
@yatna , its fine not to create an issue in this case as it is an existing GCI task. @anubhakushwaha @FarbodSalamat-Zadeh , has it been approved?

**Comment by anubhakushwaha** [comment]
@chhavip  **Yes it is approved**, *link to the task* :https://codein.withgoogle.com/dashboard/task-instances/4878424722112512/ and below is the screenshot of his work

**Comment by yatna** [comment]
@chhavip @FarbodSalamat-Zadeh Oh, sorry my fault  :-D. I often confuse the GCI PRs with the regular once.

**Comment by FarbodSalamat-Zadeh** [comment]
@yatna

No, don't worry. I should have referenced the issue in the PR. ;)

**Pull request merged**
