### PR TITLE
Fixes #291 : removing lint issues

### LINKED ISSUE #291: Fix Lint Errors
### Lint Errors
Currently, Project contains Lint issues due to which Travis build was failing with build script `gradlew build`

### Steps to reproduce the issue.
1. Used `./gradlew lint` to check all lint issues
2. Solve each lint issues under `correctness` subtag

### Expected behaviour.
Solve the lint issue so that there will be no lint error under `correctness` errors.

### Build Report
screenshot from 2018-04-18 23-02-42

### Do you want to work on the issue?
Yes

### PR DESCRIPTION
**Pull request by geekanamika**
* This PR solves lint issues coming under `correctness` section.
* Below issues still persist. 
image

### CODE REVIEW

**Comment by m-murad** [comment]
@geekanamika 
Can you please fix all the lint issues. If not, please change the title of the pr so that the issue is not closed once the pr is merged.

**Review by manishakeim — APPROVED** [review]

**Comment by m-murad** [comment]
@geekanamika 
Can you please change the base branch to gsoc18-infra

**Comment by niksj** [comment]
@m-murad should this be merged to gsoc18-infra or master branch, as this work was done prior to GSoC?
I feel gsoc-18 infra is better destination however having all the code regarding 'porting malaria app to MVP' at one place is a good idea. 
What do you say? 
@ExactlyMay looping in

**Comment by m-murad** [comment]
@niksj 
if we merge PRs in 2 branches there will be a merge conflict when we merge the 2 branches. PRs should only go in one branch.

**Comment by niksj** [comment]
@m-murad 
Yeah but how about we merge this PR to master and create a new branch from it, Anamika haven't started any work related to MVP here, but we have already existing branch gsoc18-infra(It contains some of Haroon's work merged in it)
What's your final say on this?
From my side: Having MVP related work in one branch is safer and better thing or else we can just merge all the GSoC work in the gsoc18-infra branch, this isn't going to hurt much significantly anyway.

**Comment by geekanamika** [comment]
I just changed the branch, I'll update PR by resolving merge conflicts.

**Comment by mayburgos** [comment]
@niksj I think if @geekanamika resolves the conflicts on her own, it won't be a problem to merge to gsoc18-infra. Yes or no?

But @haroonshah2764 is still working on that branch, so he may have conflicts in his next push. Do we need a gsoc18-code branch?

**Comment by geekanamika** [comment]
Shall I wait before updating the PR with resolved conflicts? I didn't actually get the whole discussion.

**Comment by niksj** [comment]
@ExactlyMay Yes, 
I think lets have gsoc18-code branch for MVP work from @geekanamika and this gsoc18-infra branch consisting lint issues by @geekanamika and UI changes' work from @haroonshah2764. Let @geekanamika resolve merge conflicts and @haroonshah2764 complete his work, thereafter gsoc18-infra branch can be merged.

**Comment by geekanamika** [comment]
@m-murad @niksj @manjumegh @ExactlyMay Currently *master* branch is most updated & when I created the PR (in may), I created the lintIssue branch from *master* branch.

After updating PR to *gsoc18-infra* (which was created from *develop* branch), It now contains 27 commits. 
25 commits are because of using master branch while creating PR as it was more updated. 
1 commit is the required & 1 commit while resolving merge conflicts.

Here's the comparison of *develop* & *master* branch which has 25 commits. https://github.com/systers/malaria-app-android/compare/develop...systers:master

What should I do now?

**Comment by geekanamika** [comment]
Closing it as gsoc18 branch is ahead, need to open another updated PR

**Pull request closed without merging**
