### PR TITLE
Done button in UserMedicineSettingsFragmentActivity faded.

### PR DESCRIPTION
**Pull request by free4murad**
Solved issue #132 

@chhavip @yatna 
please review the PR.

### CODE REVIEW

**Comment by yatna** [comment]
@free4murad can you please attach  a screenshot of how it looks now?

**Comment by free4murad** [comment]
Faded button
screenshot_20161225-092558

Enabled button
screenshot_20161225-092606

**Comment by yatna** [comment]
@free4murad In the app disabled buttons are shown with grey background with white text, See the disabled button in edit medicine activity by clicking on any future date in the calendar, you will get an idea. Change your disabled button to be consistent with that button.

**Comment by free4murad** [comment]
@yatna 
I didn't get you
Are you referring to the button marked cross in the following activity?

whatsapp image 2017-01-04 at 5 25 53 am

**Comment by yatna** [comment]
Yeah, almost like that. Also see the disabled edit button-
https://cloud.githubusercontent.com/assets/8321130/11017403/e5ccc570-85c3-11e5-824a-55003cea86bf.png

**Comment by free4murad** [comment]
@yatna I have made the requested changes.

Faded button
screenshot_20170105-215738
Active button
screenshot_20170105-215802

**Comment by yatna** [comment]
@chhavip This can me merged.

**Comment by chhavip** [comment]
@yatna @free4murad , merging. Looks good.

**Comment by free4murad** [comment]
@chhavip 
Just noticed that you have merged it in development branch.
Shouldn't it be merged in master branch?

**Comment by chhavip** [comment]
For now all commits are made to the development branch. Periodically and upon proper testing those are merged with the main branch to protect a functioning version of code.

**Pull request merged**
