### PR TITLE
PlanMyTrip bugs solved.

### PR DESCRIPTION
**Pull request by free4murad**
Solved issue #135 
@chhavip please review the PR.

### CODE REVIEW

**Comment by yatna** [comment]
Looks good @chhavip We can merge this.

**Comment by chhavip** [comment]
Merging. Good work @free4murad .

**Comment by free4murad** [comment]
@chhavip @yatna 
shall I close this PR.

**Comment by chhavip** [comment]
Close? This has been merged.

**Comment by free4murad** [comment]
@chhavip 
Sorry, intended to right it somewhere else.

**Pull request merged**
