### PR TITLE
APK size reduced.

### PR DESCRIPTION
**Pull request by free4murad**
@chhavip @yatna
The size of the generated APK is significantly reduced.
Old APK - `2,434,232 bytes (2.4 MB on disk)`
New APK - `1,676,105 bytes (1.7 MB on disk)`

Please review the PR
solves issue #164

### CODE REVIEW

**Comment by yatna** [comment]
@free4murad You are using 2 different approaches, but the issue remains the same i.e reducing apk size. A new issue for each approach will create redundancy and confusion. So close one of the either issue. While making a PR you can use all your approaches to deliver the smallest apk size achievable.

**Comment by free4murad** [comment]
@yatna 
Sure

**Comment by chhavip** [comment]
@yatna Please test on actual device to check size of reduced APK and let me know if its good to merge.

**Comment by free4murad** [comment]
@chhavip @yatna
The size of the APK has been further reduced.
[Old APK ](https://drive.google.com/open?id=0ByRo_SG_Si40N01zZk1DSmVBaUE)- `2,434,232 bytes (2.4 MB on disk)`
[New APK](https://drive.google.com/open?id=0ByRo_SG_Si40ME9nYkU1dWJ5QVU) - `1,138,700 bytes (1.1 MB on disk)`
please review the PR.

**Comment by chhavip** [comment]
Installed the new application and looks really good, can be merged! @free4murad , can you squash the commits into one? @yatna , please take a final look.

**Comment by free4murad** [comment]
@yatna @chhavip 
Squashed the commits.

**Comment by free4murad** [comment]
@yatna @chhavip 
can we please merge this?
Actually I am facing some issue while rebasing my repo, need to delete my fork and fork again.

**Comment by anubhakushwaha** [comment]
@chhavip As this PR carries changes varying throughout the app,reducing many resources,I think it can be merged :)

**Pull request merged**
