### PR TITLE
Making the Malaria app adaptive for other languages

### PR DESCRIPTION
**Pull request by Michaeldgeek**
Translated the strings.xml file to French. Also, I would suggest that all strings be put in the strings.xml file so that i can translate any change made.

### CODE REVIEW

**Comment by yatna** [comment]
@Michaeldgeek Hi, I am a fellow contributor to this repo. Having some experience in open source, I would recommend you to remove the unnecessary commits messages and remove the merge conflicts, so that the collaborators can review your work and merge/discard your PR as they seem fit. :-)

**Comment by humazed** [comment]
@yatna how could he remove the unnecessary commits messages and remove the merge conflicts,
I have the same problem. any help will be great

**Comment by yatna** [comment]
@humazed use git squash or git reset to remove unnecessary commit messages.
To resolve the merge conflicts, first pull changes from this repository to your local repository and then add your changes.

**Comment by yatna** [comment]
I think this can be a whole new feature, not only for french but for many other languages. But since we are adding new string every day, we would like to add this feature when the app is a little bit stable. For now I think @chhavip  we can close this as well.

**Pull request closed without merging**
