### PR TITLE
changed adherence level to N.A from 0% where required

### PR DESCRIPTION
**Pull request by yatna**
Earlier the screen showed adherence percentage of last 4 months. So for a users who has started the medication just 2 months before, will get 0%  for the first 2 months and then his actual adherence for the next 2 months. Since, adherence is (# of doses taken)/(# of doses that should have been taken)  so adherence must be zero only if a person takes no medicine in the entire month during his medication tenure. So, now  we display 'N.A' instead of 0% for the months not falling under the medication tenure.
This is done by storing the month in the userMedicineSettingFragmentActivity in shared preference and then comparing it with the current date. If the user specifically goes to a date before the starting date and changes then it dislays the adherence accordingly.

### CODE REVIEW

**Comment by ankita-kalra** [comment]
I understand, please attach a screenshot of it to make it more apparent. I think it would be better if those progress bars are grayed out to maintain the consistency of app gui.

**Comment by rosariorobinson** [comment]
What is status of this PR?

**Comment by yatna** [comment]
Initially when the user visits the secondFragment for the first time , the data for initial 3 months is not available and the adherence for that month is zero.
screenshot_2015-11-02-14-34-00

As the user takes his/her medicines the adherence level for that month increases accordingly.
screenshot_2015-11-02-14-34-29

If the user goes to a date of the previous month and changes to "taken" the adherence level shows accordingly.
screenshot_2015-11-02-14-35-32

**Comment by ankita-kalra** [comment]
this looks good!

**Comment by ankita-kalra** [comment]
Just needed to confirm one thing before merging, have you disabled the progress bars or they show N.A?

**Comment by yatna** [comment]
No they are not disabled, they are still clickable . However they show N.A and a change in colour.

**Comment by yatna** [comment]
This one is complete and without any merge conflict.

**Pull request merged**
