### PR TITLE
Guidelines for contributors

### PR DESCRIPTION
**Pull request by yatna**
Updated README.md by adding general guidelines to be followed while making contributions to malaria-app-android.

### CODE REVIEW

**Comment by yatna** [comment]
@chhavip Kindly, merge this.

**Comment by chhavip** [comment]
@yatna  Some further points about adding a proper title and description to the PR, need of appropriate screenshots or steps to reproduce while opening issue can also be added. Also to test an issue on atleast two devices (or emulator) before submitting and mention Android build version in issue to ensure the global or specific nature of the issue. Will be good to add these points too,

**Comment by free4murad** [comment]
@chhavip
should we create a template for issues and PRs?
screen shot 2017-01-08 at 1 34 35 pm

Something like this. This text automatically appears in the textbox when new issue or PR is created.

**Comment by free4murad** [comment]
If you want I can make  PR for this.

**Comment by chhavip** [comment]
@free4murad , sounds good, let the current work by @yatna get merged and then you can work on your PR.

**Comment by free4murad** [comment]
@chhavip 
sure

**Comment by chhavip** [comment]
@yatna what is the progress on this?

**Comment by anubhakushwaha** [comment]
@yatna Willing to add the points mentioned?

**Comment by free4murad** [comment]
@anubhakushwaha 
If @yatna is not working on this, can i?

**Comment by anubhakushwaha** [comment]
@free4murad Let's wait a day more for @yatna response else you can take up the work :)Wait for a day and then I will merge this PR after which you can work along with the points mentioned by @chhavip as well.

**Comment by anubhakushwaha** [comment]
@free4murad Go ahead.

**Pull request merged**
