### PR TITLE
Fixes #308 : Changes all hardcore values

### LINKED ISSUE #308: Change all the hardcore dimen values into dimens.xml
Right now, there are lots of hardcore values used in the code. So I would like to move them and use from the dimen file directly for the efficiency of the app.

### PR DESCRIPTION
**Pull request by yatri1609**
Changed the hardcore values into dimen.xml

@geekanamika @m-murad Please review this.

### CODE REVIEW

**Review by r00pal — APPROVED** [review]

**Review by isabelcosta — COMMENTED** [review]
@yatri1609 I think .idea/ files should not be in the PR. Can you leave those files out?

**Comment by yatri1609** [comment]
@isabelcosta Ya sure I'll do that

**Review by geekanamika — CHANGES_REQUESTED** [review]
@yatri1609  Shift this PR to `gsoc18- code` branch and remove merge conflicts if any. Also, As @isabelcosta suggested,  remove .idea files. 
If you can't complete the work,let us know, we can close PR & make it available for other contributors to claim it.

**Comment by geekanamika** [comment]
@yatri1609 Closing this PR due to no update, feel free to claim one issue with available label.

**Pull request closed without merging**
